### ISSUE TITLE
Use other than commits?

### ISSUE THREAD

**Issue by ariv797** [johnnyhuy/actions-discord-git-webhook#4]
According to the documentation, it only posts commit information. Are they any plans to support things like PRs, issues, security vulnerabilities?

**Comment by johnnyhuy** [comment]
Hey @ariv797 , no major plans to introduce additional events at the moment. However, we're open to contributions where possible.

I'm currently doing a re-write to add unit tests to this project. Perhaps after that, we can add these features 🙏
